### ISSUE TITLE
make tickets prettier 

### ISSUE THREAD

**Issue by joshuamontras** [karmagrove/karmacircle#38]
The tickets aren't pretty enough. 
![screen shot 2015-12-02 at 5 00 18 pm](https://cloud.githubusercontent.com/assets/59794/11546980/30aff840-9916-11e5-9fa3-c639beb1ef49.png)

**Comment by joshuamontras** [comment]
Ticket location is /views/user_mailer/send_event_ticket.html.erb

**Comment by joshuamontras** [comment]
To be as pretty as the ones on event brite...
![screen shot 2015-12-02 at 5 03 05 pm](https://cloud.githubusercontent.com/assets/59794/11547032/955ca360-9916-11e5-8305-6d724bb63253.png)
![screen shot 2015-12-02 at 5 02 56 pm](https://cloud.githubusercontent.com/assets/59794/11547033/956f682e-9916-11e5-8ddb-f10c4df47f6a.png)

**Comment by fabianrios** [comment]
![screenshot-tickets](https://cloud.githubusercontent.com/assets/1442115/11763797/c34f4426-a0e6-11e5-85d9-6759b758c358.png)
this will work even in old email clients and devices.

**Comment by joshuamontras** [comment]
can you issue pull request?

**Comment by joshuamontras** [comment]
NICE - it Auto references on merge.
