### ISSUE TITLE
create invoice email design

### ISSUE THREAD

**Issue by fabianrios** [karmagrove/karmacircle#43]
![receipt](https://cloud.githubusercontent.com/assets/1442115/11763799/fec6dc26-a0e6-11e5-9bbb-b692bf0cdc46.png)

we can break down more the fees

**Comment by mantras** [comment]
Good idea.  Like the fees for stripe credit card processing and the fees to karmagrove.  If you put in those columns I will get the data in there.  It's on the stripe payment object and the donationPayment object (think that's what it's called)

Your faithful servant,

Joshua
