### ISSUE TITLE
Emails To Send Post Transaction

### ISSUE THREAD

**Issue by joshuamontras** [karmagrove/karmacircle#9]
I have two preferences here to make clear as your first customer:

(1) I want a receipt in my email box for the successful transaction and to know when the complete amount will be in my bank account (or approximately when).
(2) I want to know that my customers will receive a receipt and I want to see the content of that email receipt.

**Comment by mantras** [comment]
https://github.com/karmagrove/karmacircle/issues/10 <https://github.com/karmagrove/karmacircle/issues/10>

noted.
